name: Release

on:
  push:
    tags:
      - 'v[0-9]*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get tag message
        id: get_tag_message
        run: |
          TAG_NAME=${{ github.ref }}
          TAG_MESSAGE=$(git tag -l --format='%(contents)' $TAG_NAME)
          echo "tag_message=$TAG_MESSAGE" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.get_tag_message.outputs.tag_message}} 
